Feature branch
lirad/ruby-bubble-sort pull request #1
Opened 2020-08-18 15:25 UTC by lirad

In this project, we created two sorting algorithms Bubble Sort, to arrays by number and Bubble Sort By, to sort strings:
- Created Bubble Sort method
- Created Bubble Sort By method
- Output the results with test cases

2020-08-18 17:28 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to all possible scenarios, you required to do these changes, listed below:

- [x] Check the inline comments

### Summary

-  Check all the possible scenarios listed in the inline comments 

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-18 17:28 UTC, bertil291utn commented on bubble_sort.rb
> +
## Bubble_sort
- This function should return an array. Follow this [example](https://github.com/bertil291utn/bubble-sort-project/blob/master/bubble_sort_algorithm.rb)
- Then try to check this test
```ruby
unsorted = (1..10).to_a.reverse!
bubble_sort(unsorted))
# should be equal to  
unsorted.sort
```

2020-08-18 17:28 UTC, bertil291utn commented on bubble_sort.rb
> +end
## Bubble_sort_by
- [ ] This function should return an array. Follow this [example](https://github.com/bertil291utn/bubble-sort-project/blob/master/bubble_sort_algorithm.rb)
- [ ] Try testing this scenario

```ruby
unsorted=%w[hi hello hey]
bubble_sort_by(unsorted) { |left, right| left.length - right.length })
# should be equal to 
%w[hi hey hello]
```

2020-08-18 17:28 UTC, bertil291utn commented on bubble_sort.rb
> +bubble_sort_by(string_arr) { puts "Sorted String: #{string_arr}" }
## Debugging instructions
- No debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)
  - [ ] Once you finished you must remove all debugging

2020-08-18 17:28 UTC, bertil291utn commented on bubble_sort.rb
> +bubble_sort(integer_arr) { puts "Sorted Integer: #{integer_arr}" }
## Debugging instructions
- No debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)
  - [ ] Once you finished you must remove all debugging

2020-08-19 18:14 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

Please make the correct use of `yield`.

Check the comments below.

2020-08-19 18:14 UTC, tirthajyoti-ghosh commented on bubble_sort.rb
> +end
You are calling `yield` inside the `bubble_sort` method where you don't need it. Please remove it.

2020-08-19 18:14 UTC, tirthajyoti-ghosh commented on bubble_sort.rb
> +bubble_sort(integer_arr) { puts "Sorted Integer: #{integer_arr}" }
`bubble_sort` method should not accept a block. Please remove this as well.

2020-08-19 18:14 UTC, tirthajyoti-ghosh commented on bubble_sort.rb
> +end
You are calling the `yield` in the wrong place. The `yield` keyword invokes the block that is passed to the `bubble_sort_by` method when called.

2020-08-19 18:14 UTC, tirthajyoti-ghosh commented on bubble_sort.rb
> +bubble_sort_by(string_arr) { puts "Sorted String: #{string_arr}" }
This method should accept a condition inside the block that will determine "how" to sort the array passed as a parameter.

2020-08-20 11:44 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-08-20 12:20 UTC, merged